#!/bin/bash

apt-get update \
&& apt-get install -yqq --no-install-recommends libcups2-dev gcc python3-dev \ 
&& pip install --no-cache-dir pycups \
&& apt-get purge -yqq libcups2-dev gcc python3-dev
